# Generated by Django 6.0.5 on 2026-05-24 11:09

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('emission_source', models.CharField(help_text='e.g., electricity, flight, diesel_generator', max_length=100)),
                ('raw_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=50)),
                ('standardized_value', models.DecimalField(blank=True, decimal_places=4, help_text='Standardized to metric, e.g., tCO2e or kWh', max_digits=19, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20)),
                ('suspicion_reason', models.TextField(blank=True, help_text='Populated if flagged during parsing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawDataPayload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_identifier', models.CharField(help_text='e.g., SAP_ALV, UTILITY_PORTAL, CONCUR_WEBHOOK', max_length=100)),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Exact untampered data payload/row')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='e.g., STATUS_CHANGED_TO_APPROVED, PARSING_FLAGGED', max_length=255)),
                ('previous_state', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('new_state', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who made the change. Null for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.normalizedrecord')),
            ],
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_payload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_record', to='ingestion.rawdatapayload'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.tenant'),
        ),
    ]
