# Generated by Django 6.0.5 on 2026-05-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.CharField(blank=True, help_text='Specific value after edit', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_value',
            field=models.CharField(blank=True, help_text='Specific value before edit', max_length=255, null=True),
        ),
    ]
